### ISSUE TITLE
Issue observed while installing pcs from source on x86_64 Ubuntu 14.04 

### ISSUE THREAD

**Issue by abhishek-work** [feist/pcs#66]
Hi, I installed the pcs from source on x86_64 Ubuntu 14.04.
Following are the steps that I follow to install pcsd:
	$ git clone https://github.com/feist/pcs.git
	$ cd pcs/ && make install
	$ cd pcsd/ && make get_gems
	$ cd ../ && make install pcsd.

But while running the pcs, I am getting the following error:

	$ pcs --debug cluster auth ubuntu
	Username: hacluster
	Password:
	Running: /usr/bin/ruby -I/usr/lib/pcsd/ /usr/lib/pcsd/pcsd-cli.rb read_tokens
	--Debug Input Start--
	{}
	--Debug Input End--

	Return Value: 1
	--Debug Output Start--
	/usr/bin/ruby: No such file or directory -- /usr/lib/pcsd/pcsd-cli.rb (LoadError)

	--Debug Output End--

	Sending HTTP Request to: https://localhost:2224/run_pcs
	Data: command=%5B%22--debug%22%2C+%22cluster%22%2C+%22auth%22%2C+%22ubuntu%22%2C+%22-u%22%2C+%22hacluster%22%2C+%22-p%22%2C+%22root%22%5D
	Response Reason: [Errno 111] Connection refused
	Error: Unable to connect to localhost ([Errno 111] Connection refused)

The reason for the above LoadError observed is, the file is installed in /usr/share/pcsd dir but it is expected in /usr/lib/pcsd.
Kindly provide me pointers towards resolving the issue, if any.

**Comment by tomjelinek** [comment]
Hi,
can you try running make with install_settings=true like this:
```
$ make install install_settings=true
$ cd pcsd/ && make get_gems
$ cd ../ && make install pcsd install_settings=true
```
You may need to pull recent commits before you run the commands.

**Comment by huikang** [comment]
@tomjelinek after I run the commends you posted, I got the following error on ubuntu 14

--Debug Input Start--
{"username": "hacluster", "local": false, "nodes": ["vosklab14"], "password": "temp4now", "force": false}
--Debug Input End--

Return Value: 1
--Debug Output Start--
/var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:37:in `exec': Permission denied - ../pcs/pcs (Errno::EACCES)
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:37:in `block in popen4'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:85:in `call'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:85:in `block in do_popen'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:62:in `fork'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:62:in `do_popen'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:34:in `popen4'
	from /usr/share/pcsd/pcs.rb:975:in `run_cmd_options'
	from /usr/share/pcsd/pcs.rb:959:in `run_cmd'
	from /usr/share/pcsd/pcs.rb:534:in `get_corosync_nodes'
	from /usr/share/pcsd/pcs.rb:1123:in `pcs_auth'
	from /usr/share/pcsd/pcsd-cli.rb:76:in `block in <main>'
	from /usr/share/pcsd/pcsd-cli.rb:133:in `call'
	from /usr/share/pcsd/pcsd-cli.rb:133:in `<main>'

--Debug Output End--
Error: Unable to communicate with pcsd

**Comment by tomjelinek** [comment]
@huikang can you try it again with the most recent version? I fixed paths for debian https://github.com/feist/pcs/commit/51d04363bf32b1cc57f13216b1653aa3ed08986c and there was another fix for pcs/pcsd path issues before.

**Comment by huikang** [comment]
@tomjelinek I pull the from the latest git and install pcsd as the following steps

# cd pcsd ; make get_gems ; cd ..
# make install_pcsd
Then I start pcsd as "service pcsd start", I can see pcsd is running. 

root@vosklab11:/tmp/sdebuilder/pcs# service pcsd status
 * pcsd is running



But the error still exits

root@vosklab11:/tmp/sdebuilder/pcs# pcs --debug cluster -u hacluster -p temp4now auth vosklab11
Running: /usr/bin/ruby -I/usr/share/pcsd/ /usr/share/pcsd/pcsd-cli.rb auth
--Debug Input Start--
{"username": "hacluster", "local": false, "nodes": ["vosklab11"], "password": "temp4now", "force": false}
--Debug Input End--

Return Value: 1
--Debug Output Start--
/var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:37:in `exec': Permission denied - ../pcs/pcs (Errno::EACCES)
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:37:in `block in popen4'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:85:in `call'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:85:in `block in do_popen'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:62:in `fork'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:62:in `do_popen'
	from /var/lib/gems/1.9.1/gems/open4-1.3.4/lib/open4.rb:34:in `popen4'
	from /usr/share/pcsd/pcs.rb:975:in `run_cmd_options'
	from /usr/share/pcsd/pcs.rb:959:in `run_cmd'
	from /usr/share/pcsd/pcs.rb:534:in `get_corosync_nodes'
	from /usr/share/pcsd/pcs.rb:1123:in `pcs_auth'
	from /usr/share/pcsd/pcsd-cli.rb:76:in `block in <main>'
	from /usr/share/pcsd/pcsd-cli.rb:133:in `call'
	from /usr/share/pcsd/pcsd-cli.rb:133:in `<main>'

--Debug Output End--

Error: Unable to communicate with pcsd

output from ps.log


::ffff:172.16.1.11 - - [27/Aug/2015:16:37:46 +0000] "POST /remote/auth HTTP/1.1" 200 36 0.0290
::ffff:172.16.1.11 - - [27/Aug/2015:16:37:46 +0000] "POST /remote/auth HTTP/1.1" 200 36 0.0291
vosklab11 - - [27/Aug/2015:16:37:46 UTC] "POST /remote/auth HTTP/1.1" 200 36
- -> /remote/auth
I, [2015-08-27T16:38:10.469060 #23092]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2015-08-27T16:38:10.469185 #23092]  INFO -- : CIB USER: hacluster, groups: 
I, [2015-08-27T16:38:10.480207 #23092]  INFO -- : Return Value: 0
I, [2015-08-27T16:38:10.480865 #23092]  INFO -- : Attempting login by 'hacluster'
I, [2015-08-27T16:38:10.493841 #23092]  INFO -- : Running: id -Gn hacluster
I, [2015-08-27T16:38:10.493921 #23092]  INFO -- : CIB USER: hacluster, groups: 
I, [2015-08-27T16:38:10.497004 #23092]  INFO -- : Return Value: 0
I, [2015-08-27T16:38:10.497063 #23092]  INFO -- : Successful login by 'hacluster'
::ffff:172.16.1.11 - - [27/Aug/2015:16:38:10 +0000] "POST /remote/auth HTTP/1.1" 200 36 0.0291
::ffff:172.16.1.11 - - [27/Aug/2015:16:38:10 +0000] "POST /remote/auth HTTP/1.1" 200 36 0.0292
vosklab11 - - [27/Aug/2015:16:38:10 UTC] "POST /remote/auth HTTP/1.1" 200 36
- -> /remote/auth
I, [2015-08-27T16:38:38.634271 #23092]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2015-08-27T16:38:38.634381 #23092]  INFO -- : CIB USER: hacluster, groups: 
I, [2015-08-27T16:38:38.639967 #23092]  INFO -- : Return Value: 0
I, [2015-08-27T16:39:38.641142 #23092]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2015-08-27T16:39:38.641310 #23092]  INFO -- : CIB USER: hacluster, groups: 
I, [2015-08-27T16:39:38.651277 #23092]  INFO -- : Return Value: 0
I, [2015-08-27T16:40:38.651770 #23092]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2015-08-27T16:40:38.651906 #23092]  INFO -- : CIB USER: hacluster, groups: 
I, [2015-08-27T16:40:38.659910 #23092]  INFO -- : Return Value: 0

**Comment by tomjelinek** [comment]
@huikang you need to run `make install_pcsd install_settings=true` instead of `make install_pcsd` otherwise the debian specific files won't be used. See https://github.com/feist/pcs/issues/66#issuecomment-126233925

Also logs in your messages are very hard to read. If you put them in between lines containing nothing but ``` it will be much more readable, like this:

```
rh71-node1 - - [28/Aug/2015:09:18:51 CEST] "POST /remote/auth HTTP/1.1" 200 36
- -> /remote/auth
I, [2015-08-28T09:18:52.548611 #439]  INFO -- : Running: /usr/sbin/corosync-cmapctl totem.cluster_name
I, [2015-08-28T09:18:52.548781 #439]  INFO -- : CIB USER: hacluster, groups: 
I, [2015-08-28T09:18:52.556593 #439]  INFO -- : Return Value: 0
```

**Comment by huikang** [comment]
@tomjelinek 

```
root@vosklab11:~/pcs# make install_pcsd install_settings=true
make -C pcsd build_gems
grep: /etc/redhat-release: No such file or directory
make[1]: Entering directory `/root/pcs/pcsd'
bundle install --local --deployment
Using backports (3.6.4) 
Using eventmachine (1.0.7) 
Using monkey-lib (0.5.4) 
Using multi_json (1.11.1) 
Using open4 (1.3.4) 
Using orderedhash (0.0.6) 
Using rack (1.6.4) 
Using rack-protection (1.5.3) 
Using rack-test (0.6.3) 
Using rpam-ruby19 (1.2.1) 
Using tilt (1.4.1) 
Using sinatra (1.4.6) 
Using sinatra-contrib (1.4.4) 
Using sinatra-sugar (0.5.1) 
Using bundler (1.3.5) 
Updating files in vendor/cache
Your bundle is complete!
It was installed into ./vendor/bundle
make[1]: Leaving directory `/root/pcs/pcsd'
mkdir -p /var/log/pcsd
mkdir -p /usr/share/
cp -r pcsd /usr/share/
install -m 644 -D pcsd/pcsd.conf /etc/default/pcsd
install -d /etc/pam.d
install  pcsd/pcsd.pam.debian /etc/pam.d/pcsd
rm -f  /usr/share/pcsd/settings.rb
install -m755 pcsd/settings.rb.x86_64-linux-gnu.debian /usr/share/pcsd/settings.rb
install -m 755 -D pcsd/pcsd.debian //etc/init.d/pcsd
install -m 700 -d /var/lib/pcsd
install -m 644 -D pcsd/pcsd.logrotate /etc/logrotate.d/pcsd
```

This time I found that pcsd can not even be started

```
root@vosklab11:~/pcs# service pcsd start
 * Starting pcs daemon pcsd                                                                PID is 6459
Daemon died immediately after starting. Please check your logs and configurations.
                                                                                    [fail]
```

My OS is 
```
root@vosklab11:~/pcs# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

```

However, if I install with ```make install_pcsd```, ```service pcsd start``` successes.

**Comment by tomjelinek** [comment]
@huikang Debian specific files were missing some lines, I'm sorry for that. I just fixed that.

**Comment by huikang** [comment]
@tomjelinek Thanks for your quick response. It works now. I suggest to document these steps for Debian in the README if you have not done so. Thanks.

```
$ make install install_settings=true
$ cd pcsd/ && make get_gems
$ cd ../ && make install_pcsd install_settings=true
```
